There are several different ways you can customize and configure how the `SessionFactory` is built. The easiest way is via configuration. The following configuration demonstrates an example:

[configuration]
.Configuring Hibernate Properties
----
datasources:
    default:
        name: 'mydb'
jpa:
    default:
        entity-scan:
            packages:
                - 'foo.bar'
                - 'foo.baz'
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: true
----

The above example configures the packages to be scanned and sets properties to be passed to Hibernate. As you can see these are done on a per `DataSource` basis. Refer to the api:configuration.hibernate.jpa.JpaConfiguration[] configuration class for the possible options.

==== Controlling DataSource Lookup

By default, Micronaut will automatically lookup and inject a DataSource bean into Hibernate's configuration. In some scenarios, you may want to disable this behavior, such as:

* When using Hibernate Reactive (which uses a different connection mechanism)
* When the database connection is managed externally
* When providing connection details directly through Hibernate properties (e.g., JDBC URL in properties)

You can control this behavior using the `allowDataSourceLookup` configuration property:

[configuration]
.Disabling DataSource Lookup
----
jpa:
    default:
        allowDataSourceLookup: false
        properties:
            hibernate:
                connection:
                    url: jdbc:h2:mem:mydb
                    username: sa
                    password: ''
----

This setting can be configured globally or per datasource:

[configuration]
.Per-DataSource Configuration
----
jpa:
    default:
        allowDataSourceLookup: true  # Use injected DataSource
    other:
        allowDataSourceLookup: false # Manage connection externally
        properties:
            hibernate:
                connection:
                    url: jdbc:postgresql://localhost/otherdb
----

NOTE: When `allowDataSourceLookup` is set to `false`, you must provide connection information through Hibernate properties or use an alternative connection mechanism (such as Hibernate Reactive's Vert.x SQL client).

==== Advanced Customization

If you need even further control over how the `SessionFactory` is built then you can register api:context.event.BeanCreatedEventListener[] beans that listen for the creation of the link:{hibernateapi}/org/hibernate/boot/SessionFactoryBuilder.html[SessionFactoryBuilder], link:{hibernateapi}/org/hibernate/boot/MetadataSources.html[MetadataSources] etc. and apply your custom configuration in the listener.

You may also optionally create beans of type link:{hibernateapi}/org/hibernate/integrator/spi/Integrator.html[Integrator] and link:{hibernateapi}/org/hibernate/Interceptor.html[Interceptor] and these will be picked up and injected automatically.
